# Generated by Django 5.0.6 on 2024-06-26 08:39

import books.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(max_length=13, unique=True, validators=[django.core.validators.MinLengthValidator(13, message='ISBN must be 13 digits long.'), books.validators.validate_isbn13]),
        ),
    ]
