# Generated by Django 5.0.6 on 2024-06-26 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_author_birth_year_alter_author_name_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
